---
title: "step1_1.rmd"
author: "Dominick J. Lemas"
date: "2022-09-26"
output: html_document
---

```{r setup, include=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(readr)
```

```{r import}

# **************************************************************************** #
# ***************              Open    Data                    *************** #
# **************************************************************************** #

# import data created by step1_0.py
chain <- read_tsv("~/CAMP/data_prepare/step1/pdb_pep_chain")

fasta <- read_tsv("~/CAMP/data_prepare/step1/pdbid_all_fasta")


```

```{r import}

# **************************************************************************** #
# ***************              Subset to Demo Data             *************** #
# **************************************************************************** #

# PPDbench: https://webs.iiitd.edu.in/raghava/ppdbench/dataset.php
# ligands (133)

pdb_id_demo=c("1cjr","1cka","1cvu","1d4t","1eg4","1h6w","1hc9")
              


# pdb_id_chain=c("1cjr_a","1cka_b","1cvu_f","1d4t_b","1eg4_p","1h6w_b","1hc9_c")


# subset data
demo.c <- chain %>%
  filter(PDB_id %in% pdb_id_demo) %>%
   write_delim(file="pdb_pep_chain_demo", delim = "\t")

# subset data
demo.f <- fasta %>%
  filter(PDB_id %in% pdb_id_demo) %>%
  write_delim(file="pdbid_all_fasta_demo", delim = "\t")



```

