FROM ubuntu:latest
MAINTAINER Dominick Lemas djlemas@ufl.edu

RUN apt update && apt -y install \
   build-essential \
   wget  

RUN wget http://www.sbeams.org/sample_data/Microarray/External_test_data.tar.gz 
RUN tar -xvf External_test_data.tar.gz  

RUN mkdir -p /blue /orange /scratch/local /share